[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/joshmaglione/CS102-Jupyter/main?labpath=.%2FWeek04.ipynb) (?m?s to load)

<a href="https://colab.research.google.com/github/joshmaglione/CS102-Jupyter/blob/main/Week04.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> (Google account needed)

# Week 4: Universal functions and broadcasting

*Universal functions* (or UFuncs) are operations applied to `ndarray`. 

Operations are generally unary (takes one argument) or binary (takes two arguments).

## What do we mean by operations?

For example: $v = (2, -3, 0, 9)$.

Unary operation of $-$
$$
    -v = (-2, 3, 0, -9).
$$

Binary operation of $+$
$$
    v+v = (4, -6, 0, 18).
$$

NumPy has asserted that multiplication of `ndarray` are to be *component-wise*. 

There is no canonical choice of what multiplication should be, but this is a useful choice in practice. 

Continuing our example: $*$ is a binary operation
$$
    v * v = (3, 9, 0, 81). 
$$

Of course so is division, but this would not work for our specific $v$. 

## Time comparisons

Last week, we saw hints of NumPy being significantly faster than Python at running through elements of containers.

Apparently, this isn't always true, at least for Python 3.12.

In [1]:
import numpy as np

Let's create large arrays (but still small compared to real-world examples). 

In [2]:
N = 10^9
apy = range(1, N + 1)
bpy = range(2, N + 2)
anp = np.arange(1, N + 1)
bnp = np.arange(2, N + 2)

Let's multiply both vectors.

In [3]:
%timeit _ = [apy[i] * bpy[i] for i in range(N)]

234 ns ± 6.08 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


We will use a UFunc here.

In [4]:
%timeit _ = anp * bnp

233 ns ± 1.03 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


**Fun fact.** I ran the above cells on my MacBook Pro which has an [Apple M2](https://en.wikipedia.org/wiki/Apple_M2) chip, and the speeds are essentially the same! 

In [5]:
apy = [np.random.randint(1, 100) for _ in range(N)]
bpy = [np.random.randint(1, 100) for _ in range(N)]
anp = np.random.randint(1, 100, size=N)
bnp = np.random.randint(1, 100, size=N)

In [6]:
%timeit _ = [apy[i] * bpy[i] for i in range(N)]

139 ns ± 2.93 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [7]:
%timeit _ = anp * bnp

238 ns ± 0.496 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Although Python might perform on par with NumPy, it is safer to just use NumPy if performance might be an issue.

## Ufuncs now, seriously

NumPy offers many *vectorized* alternatives to the usual operations.

The point is that this pushes the loop down into the compiled C code, resulting in a more efficient execution. 

NumPy has over [60 Ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs).

Ufuncs are easy to use: just apply the operation on arrays

In [8]:
a = np.random.randint(1, 10, size=3)
b = np.random.randint(1, 10, size=3)
c = a + b
print(f"    array a = {a}")
print(f"    array b = {b}")
print(f"array a + b = {c}")

    array a = [9 3 6]
    array b = [5 6 6]
array a + b = [14  9 12]


More of the usual mathematical operations

In [9]:
print(a * b)

[45 18 36]


In [10]:
print(a / b)

[1.8 0.5 1. ]


In [11]:
print(a // b)

[1 0 1]


In [12]:
print(2**a)         # this is the exponentiation operation.

[512   8  64]


In [13]:
print(a**2)

[81  9 36]


In [14]:
# print(a**(-1))      # Won't convert

If we want to change the data type (`dtype`) of an array, best to use `astype` method.

In [18]:
a_fl = a.astype('f')
print(a_fl)
print(a_fl**(-1))

[9. 3. 6.]
[0.11111111 0.33333334 0.16666667]


In [20]:
print(a % 2)

[1 1 0]


Can do bitwise operations as well

In [28]:
print(~a)

[-10  -4  -7]


In [27]:
print(a^a)

[0 0 0]


From the documentation:

> Some of these ufuncs are called automatically on arrays when the relevant infix notation is used (e.g., `add(a, b)` is called internally when `a + b` is written and `a` or `b` is an ndarray).
>
> Nevertheless, you may still want to use the **ufunc call** in order to use the optional output argument(s) to place the output(s) in an object (or objects) of your choice.

In [29]:
print(a + b)
print(np.add(a, b))

[14  9 12]
[14  9 12]


The methods can prevent additional work. 

For example, take the example where we wanted to invert an array of ints.

We can use `np.power` and specify the output `dtype` all at once.

In [30]:
np.power(a, -1, dtype='f')

array([0.11111111, 0.33333334, 0.16666667], dtype=float32)

Using the keyword argument `out`, one can specify the target output.

In [42]:
z = np.zeros(20)
np.power(2, range(10), out=z[1::2])
print(z)

[  0.   1.   0.   2.   0.   4.   0.   8.   0.  16.   0.  32.   0.  64.
   0. 128.   0. 256.   0. 512.]


Often the methods are not required, but sometimes they can be exactly the right tool.

### Trigonometric functions

In [33]:
thetas = np.linspace(0, np.pi, 3)
print(thetas)

[0.         1.57079633 3.14159265]


In [34]:
print(f"sin(theta) = {np.sin(thetas)}")
print(f"cos(theta) = {np.cos(thetas)}")
print(f"tan(theta) = {np.tan(thetas)}")

sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


One can perform the inverse trigonometric functions as well.

In [37]:
x = [-1, 0, 1]
print(f"       x  = {x}")
print(f"arcsin(x) = {np.arcsin(x)}")
print(f"arccos(x) = {np.arccos(x)}")
print(f"arctan(x) = {np.arctan(x)}")

       x  = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


### Exponentials and logarithms

We can take powers of $e$ with `np.exp`, of $2$ with `np.exp2`, or more general bases with `np.power`.

In [44]:
x = [1, 2, 3]
print(f"   x = {x}")
print(f" e^x = {np.exp(x)}")
print(f" 2^x = {np.exp2(x)}")
print(f"pi^x = {np.power(np.pi, x)}")

   x = [1, 2, 3]
 e^x = [ 2.71828183  7.3890561  20.08553692]
 2^x = [2. 4. 8.]
pi^x = [ 3.14159265  9.8696044  31.00627668]


The function `np.log` gives the natural logarithm, `np.log2` gives the base-2 logarithm, and `np.log10` gives the base-10 logarithm.

In [46]:
x = [1, 2, 4, 10]
print(f"       x = {x}")
print(f"  log(x) = {np.log(x)}")
print(f" log2(x) = {np.log2(x)}")
print(f"log10(x) = {np.log10(x)}")

       x = [1, 2, 4, 10]
  log(x) = [0.         0.69314718 1.38629436 2.30258509]
 log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


### Aggregates and Accumulations

Time for a quick journey down a rabbit hole

![](imgs/rabbit.jpg)

There is a Python module that ships with Python called `functools` (unofficially "functional tools").

In it there is a function called `reduce` which basically takes a list whose entries have a particular type $t$ and returns something of type $t$.

**Oversimplification!**

Can also think of this as *aggregating* the data.

You also need to tell `reduce` *how* to, well, reduce the list.

Two arguments:
1. a function,
2. a list,
3. (optional) a starting value.

In [49]:
from functools import reduce

# Argument 1 : a function
def add(x, y):
    return x + y

# Argument 2 : a list
a = ["Hello", "world!"]

# Argument 3 : starting value
start = ""

We can reduce our list `a` to a string using the recipe given by `add`.

In [50]:
reduce(add, a, start)

'Helloworld!'

OK back to NumPy.

Often when one uses `reduce`, a standard operation is used to reduce the list to a value.

NumPy Ufuncs have a `reduce` method builtin, so instead of calling `reduce` from `functools`, one can use a likely better performing alternative.

In [51]:
a = np.arange(10)
print(a)
np.add.reduce(a)

[0 1 2 3 4 5 6 7 8 9]


45

One should take `np.add.reduce(a)` as `reduce(add, a, 0)`.

One can set an initial value with `initial`.

In [52]:
np.add.reduce(a, initial=10)

55

In [53]:
np.multiply.reduce(a[1:])

362880

Sometimes one is not *only* interested in the final aggregated value, but instead one wants all of accumulated values at every step.

Instead of `reduce` one should use `accumulate`.

In [55]:
print(np.add.accumulate(a))

[ 0  1  3  6 10 15 21 28 36 45]


In [56]:
print(np.multiply.accumulate(a[1:]))

[     1      2      6     24    120    720   5040  40320 362880]


## Ufuncs in higher dimensions

As before, going from $1$-dimensional arrays to $2$-dimensional arrays is sometimes the tricky step. From $2$-dimensions to $n$-dimensions, it is generally straight-forward.

Ufuncs can be applied to arrays of the same *shape*.

Above we were only looking at $1$-dimensional arrays with the same number of entries (i.e. shape).

In [58]:
a = np.arange(20).reshape(4, 5)
b = np.random.randint(1, 10, size=(4, 5))
print(a)
print()
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[3 3 9 4 1]
 [8 9 9 8 4]
 [6 3 8 9 1]
 [1 1 9 2 8]]


In [60]:
print(a + b)

[[ 3  4 11  7  5]
 [13 15 16 16 13]
 [16 14 20 22 15]
 [16 17 26 20 27]]


In [61]:
print(a * b)

[[  0   3  18  12   4]
 [ 40  54  63  64  36]
 [ 60  33  96 117  14]
 [ 15  16 153  36 152]]


**WARNING:** Be aware that `<matrix> * <matrix>` is **NOT** matrix multiplication. I make this mistake all the time 🤕

For that, use the `@` operator: `<matrix> @ <matrix>`

In [63]:
# print(a @ b)      # Wrong shapes (4,5) x (4,5) is incompatible. 

In [65]:
print(np.power(2, a))

[[     1      2      4      8     16]
 [    32     64    128    256    512]
 [  1024   2048   4096   8192  16384]
 [ 32768  65536 131072 262144 524288]]


You can imagine higher dimensions and all the other Ufuncs we described (and more).

## Broadcasting

Actually, I lied, but only because I knew I would make you aware of it right now.

You **CAN** use Ufuncs beween arrays of different *shapes* and *sizes*.

**Broadcasting** is a means of taking two arrays of different shapes and sizes and making them the same shape and size.

So really, I didn't lie: Ufuncs need arrays of the same shape and size. It's just that broadcasting gets built into the function as well,so it appears not to be necessary.