[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/joshmaglione/CS102-Jupyter/main?labpath=.%2FWeek04.ipynb) (?m?s to load)

<a href="https://colab.research.google.com/github/joshmaglione/CS102-Jupyter/blob/main/Week04.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> (Google account needed)

# Week 4: Universal functions and broadcasting

*Universal functions* (or UFuncs) are operations applied to `ndarray`. 

Operations are generally unary (takes one argument) or binary (takes two arguments).

## What do we mean by operations?

For example: $v = (2, -3, 0, 9)$.

Unary operation of $-$
$$
    -v = (-2, 3, 0, -9).
$$

Binary operation of $+$
$$
    v+v = (4, -6, 0, 18).
$$

NumPy has asserted that multiplication of `ndarray` are to be *component-wise*. 

There is no canonical choice of what multiplication should be, but this is a useful choice in practice. 

Continuing our example: $*$ is a binary operation
$$
    v * v = (3, 9, 0, 81). 
$$

Of course so is division, but this would not work for our specific $v$. 

## Time comparisons

Last week, we saw hints of NumPy being significantly faster than Python at running through elements of containers.

Apparently, this isn't always true, at least for Python 3.12.

In [1]:
import numpy as np

Let's create large arrays (but still small compared to real-world examples). 

In [2]:
N = 10^9
apy = range(1, N + 1)
bpy = range(2, N + 2)
anp = np.arange(1, N + 1)
bnp = np.arange(2, N + 2)

Let's multiply both vectors.

In [3]:
%timeit _ = [apy[i] * bpy[i] for i in range(N)]

237 ns ± 6.94 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


We will use a UFunc here.

In [4]:
%timeit _ = anp * bnp

234 ns ± 0.952 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


**Fun fact.** I ran the above cells on my MacBook Pro which has an [Apple M2](https://en.wikipedia.org/wiki/Apple_M2) chip, and the speeds are essentially the same! 

In [5]:
apy = [np.random.randint(1, 100) for _ in range(N)]
bpy = [np.random.randint(1, 100) for _ in range(N)]
anp = np.random.randint(1, 100, size=N)
bnp = np.random.randint(1, 100, size=N)

In [6]:
%timeit _ = [apy[i] * bpy[i] for i in range(N)]

136 ns ± 1.24 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [7]:
%timeit _ = anp * bnp

233 ns ± 3.12 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Although Python might perform on par with NumPy, it is safer to just use NumPy if performance might be an issue.

## Ufuncs now, seriously

NumPy offers many *vectorized* alternatives to the usual operations.

The point is that this pushes the loop down into the compiled C code, resulting in a more efficient execution. 

NumPy has over [60 Ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs).

Ufuncs are easy to use: just apply the operation on arrays

In [12]:
a = np.random.randint(1, 10, size=3)
b = np.random.randint(1, 10, size=3)
c = a + b
print(f"    array a = {a}")
print(f"    array b = {b}")
print(f"array a + b = {c}")

    array a = [6 8 3]
    array b = [2 1 6]
array a + b = [8 9 9]


In [14]:
print(a * b)

[12  8 18]


In [15]:
print(a / b)

[3.  8.  0.5]


In [16]:
print(a // b)

[3 8 0]


In [20]:
print(2**a)         # this is the exponentiation operation.

[ 64 256   8]
