# Week 3: Indexing, Reshaping, and Computing with `ndarray`

From last time:
- NumPy arrays have type `ndarray`
- `ndarray`s are *homogeneous multi-dimensional* collections of data. 
- Some attributes of an `ndarray`:
  - `dtype` : the data type of the entries,
  - `ndim` : the number of dimensions, 
  - `shape` : the size of each dimension, 
  - `size` : the total size of the array

Additional attributes include:
- `itemsize` : the size (in bytes) of each array element, 
- `nbytes` : the total bytes used by the array.

## Some advantages of the `ndarray`

In [1]:
import numpy as np

### Memory efficiency

Let's look at the size (in bytes) of an instance of `ndarray`.

In [5]:
x3 = np.random.randint(10, size=(3, 2, 5)) 
print(x3)

[[[5 9 9 7 8]
  [4 1 9 9 1]]

 [[7 2 9 9 1]
  [6 3 6 0 2]]

 [[5 1 3 5 7]
  [7 1 6 5 9]]]


In [7]:
print(f"itemsize: {x3.itemsize} bytes")
print(f"nbytes: {x3.nbytes} bytes")

itemsize: 8 bytes
nbytes: 240 bytes


Significantly fewer bytes. 

In general, `nbytes` is equal to `itemsize` times `size`.

In [8]:
x3.itemsize * x3.size == x3.nbytes

True

Let's compare this with a list in Python, and let's make them larger to more easily see the difference.

In [9]:
from sys import getsizeof

# size of our lists
N = 10000

# declaring a list of 1000 elements 
S = range(N)

# getting the size of every element and the container
S_size = sum(getsizeof(x) for x in S) + getsizeof(S)

print(f"Size of the list + container: {S_size} bytes")

# declaring a Numpy array of 1000 elements 
D = np.arange(N)

# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
  
# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)
print("Size of the whole Numpy array in bytes: ",D.nbytes)

Size of the list+container in bytes:  28048
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000
Size of the whole Numpy array in bytes:  8000
